### ISSUE TITLE
[Wear More Rings] Warning about hats (?)

### ISSUE THREAD

**Issue by NightFright2k19** [bcmpinc/StardewHack#83]
Getting these warnings in my error logs, using latest WMR (v5.1) and StardewHack (v5.2):

```
[15:29:25 INFO  StardewHack] Loaded StardewHack library v5.2.0 using Harmony v2.2.1.0.
[15:29:25 DEBUG Wear More Rings] Applying bytecode patches for bcmpinc.WearMoreRings.
[15:29:25 TRACE Wear More Rings] Applying patch Ring_ctor to Void .ctor(Int32) in StardewValley.Objects.Ring.
[15:29:25 TRACE Wear More Rings] Applying patch InventoryPage_receiveLeftClick to Void receiveLeftClick(Int32, Int32, Boolean) in StardewValley.Menus.InventoryPage.
[15:29:25 TRACE Wear More Rings] StardewHack.InstructionNotFoundException: Could not find instruction sequence (failed to match line 4: "ldstr "Hat""):
  ldloc.1
  ldfld System.String StardewValley.Menus.ClickableComponent::name
  stloc.3
  ldloc.3
  brfalse
  ldloc.3
  ldstr "Hat"
   at StardewHack.InstructionRange..ctor(List`1 insts, InstructionMatcher[] contains, Int32 start, Int32 step)
   at StardewHack.WearMoreRings.ModEntry.InventoryPage_receiveLeftClick()
[15:29:25 TRACE Wear More Rings] Applying patch InventoryPage_performHoverAction to Void performHoverAction(Int32, Int32) in StardewValley.Menus.InventoryPage.
[15:29:25 TRACE Wear More Rings] StardewHack.InstructionNotFoundException: Could not find instruction sequence (failed to match line 4: "ldstr "Hat""):
  ldloc.1
  ldfld System.String StardewValley.Menus.ClickableComponent::name
  stloc.2
  ldloc.2
  brfalse
  ldloc.2
  ldstr "Hat"
   at StardewHack.InstructionRange..ctor(List`1 insts, InstructionMatcher[] contains, Int32 start, Int32 step)
   at StardewHack.WearMoreRings.ModEntry.InventoryPage_performHoverAction()
[15:29:25 TRACE Wear More Rings] Applying patch InventoryPage_draw to Void draw(Microsoft.Xna.Framework.Graphics.SpriteBatch) in StardewValley.Menus.InventoryPage.
[15:29:25 TRACE Wear More Rings] StardewHack.InstructionNotFoundException: Could not find instruction sequence (failed to match line 7: "ldstr "Hat""):
  ldloca.s
  call
  stloc.s
  ldloc.s
  ldfld System.String StardewValley.Menus.ClickableComponent::name
  stloc.s
  ldloc.s
  brfalse
  ldloc.s
  ldstr "Hat"
   at StardewHack.InstructionRange..ctor(List`1 insts, InstructionMatcher[] contains, Int32 start, Int32 step)
   at StardewHack.WearMoreRings.ModEntry.InventoryPage_draw()
```

**Comment by bcmpinc** [comment]
The mod is working correctly. Those are trace logs. Debugging information for when something goes wrong later down the line. It basically means that one version of a patch failed so it tried a different version that did work. So everything's still fine. It's a left over from when there were differences between the windows and linux builds.
